In [13]:
import numpy as np

In [14]:
def normalize(a):
    return a/sum(a)

In [15]:
A = np.array([
        [0, 1/4, 1/4,   0,   0,   0,   0,   0, 0],
        [1,   0,   0,   0,   0,   0,   0,   0, 0],
        [0,   0,   0, 1/2, 3/4,   0,   0,   0, 0],
        [0, 3/4, 3/4,   0,   0,   0,   0,   0, 0],
        [0,   0,   0,   0,   0, 1/2,   1,   0, 0],
        [0,   0,   0, 1/2, 1/4,   0,   0,   0, 0],
        [0,   0,   0,   0,   0,   0,   0, 3/4, 1],
        [0,   0,   0,   0,   0, 1/2,   0,   0, 0],
        [0,   0,   0,   0,   0,   0,   0, 1/4, 0]
])

In [16]:
for i in range(len(A)):
    A[0, i] = 0

In [17]:
for i in range(1, len(A)):
    A[i, i] -= 1
    
A[0, 0] = 1

In [18]:
B = np.zeros(len(A))
#for i in range(len(A)):
#    B[i] = 1/len(A)
B[0] = 1

In [19]:
A, B

(array([[ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 1.  , -1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -1.  ,  0.5 ,  0.75,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.75,  0.75, -1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  , -1.  ,  0.5 ,  1.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.5 ,  0.25, -1.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -1.  ,  0.75,  1.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 ,  0.  , -1.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.25, -1.  ]]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [20]:
stat = np.linalg.solve(A, B)
stat

array([1.  , 1.  , 3.  , 3.  , 2.  , 2.  , 1.  , 1.  , 0.25])

In [21]:
stat = np.array([stat[0], stat[1] + stat[2], stat[3] + stat[4], stat[5] + stat[6], stat[7]+stat[8]])
stat = normalize(stat)
stat

array([0.07017544, 0.28070175, 0.35087719, 0.21052632, 0.0877193 ])

In [22]:
stateSpace = np.array([-2, -1, 0, 1, 2])

In [23]:
np.dot(stat, stateSpace)

-0.03508771929824567

In [24]:
sum(stat)

1.0