In [ ]:
import sys
sys.path.append("../")

In [48]:
import numpy as np

In [49]:
def printStationaryAndµAsFractions(stationary, mu):
    s = sum(stationary)
    sstat = ['%d/%d' % (x, s) for x in stationary]
    print(', '.join(sstat))
    print('µ = %d/%d' % (mu, s))

In [36]:
def normalize(a):
    return a/sum(a)

In [37]:
A = np.array([
        [0, 1/4, 1/4,   0,   0,   0,   0,   0, 0, 0],
        [1,   0,   0,   0,   0,   0,   0,   0, 0, 0],
        [0,   0,   0, 1/2, 3/4,   0,   0,   0, 0, 0],
        [0, 3/4, 3/4,   0,   0,   0,   0,   0, 0, 0],
        [0,   0,   0,   0,   0, 1/2,   1,   0, 0, 0],
        [0,   0,   0, 1/2, 1/4,   0,   0,   0, 0, 0],
        [0,   0,   0,   0,   0,   0,   0, 3/4, 1, 0],
        [0,   0,   0,   0,   0, 1/2,   0,   0, 0, 0],
        [0,   0,   0,   0,   0,   0,   0,   0, 0, 1],
        [0,   0,   0,   0,   0,   0,   0, 1/4, 0, 0]
])

In [38]:
for i in range(len(A)):
    A[0, i] = 0

In [39]:
for i in range(1, len(A)):
    A[i, i] -= 1
    
A[0, 0] = 1

In [40]:
B = np.zeros(len(A))
B[0] = 1

In [41]:
print(A)
B

[[ 1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 1.   -1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -1.    0.5   0.75  0.    0.    0.    0.    0.  ]
 [ 0.    0.75  0.75 -1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -1.    0.5   1.    0.    0.    0.  ]
 [ 0.    0.    0.    0.5   0.25 -1.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.   -1.    0.75  1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.5   0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.   -1.    1.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.25  0.   -1.  ]]


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
stat = np.linalg.solve(A, B)
stat

array([ 4.,  4., 12., 12.,  8.,  8.,  4.,  4.,  1.,  1.])

In [43]:
stat = np.array([stat[0], stat[1] + stat[2], stat[3] + stat[4], stat[5] + stat[6], stat[7]+stat[8], stat[9]])
stat = normalize(stat)
stat

array([0.06896552, 0.27586207, 0.34482759, 0.20689655, 0.0862069 ,
       0.01724138])

In [44]:
stateSpace = np.array([-2, -1, 0, 1, 2, 3])

In [45]:
np.dot(stat, stateSpace)

0.017241379310344758

In [54]:
stat = np.linalg.solve(A, B)
stat = stat*4
stat = np.array([stat[0], stat[1] + stat[2], stat[3] + stat[4], stat[5] + stat[6], stat[7]+stat[8], stat[9]])
stat = np.rint(stat).astype(int)
stateSpace = np.array([-2, -1, 0, 1, 2, 3])
mu = np.dot(stat, stateSpace)
printStationaryAndμAsFractions(stat, np.rint(mu).astype(int))

4/58, 16/58, 20/58, 12/58, 5/58, 1/58
µ = 1/58


In [55]:
print(1/58)

0.017241379310344827
